# Ergänzende Tabellenzeilen für seed_cybrain_hyluron_it_ot.py (deutsch, IT/OT-Domäne)
# DEV: (nr, title, event_date, sop, description, root_cause, ext_status, impact, category, site)

DEV_11_45: list[tuple] = [
    (11, "Firewall-Regel zu permissiv", "2024-05-22", "SOP-IT-002",
     "IT→OT Port 22/SSH für alle IT-Accounts statt nur hardening-Abteilung; Least-Privilege verletzt.",
     "Initiale Regelmigration 2023, Gruppen-Zuordnung zu breit, kein halbjährlicher Least-Privilege-Workshop.",
     "closed", "major", "IT/OT Sicherheit", "Werk-01"),
    (12, "Keine Segmentierung Fermentation/Abfüllung", "2024-06-30", "SOP-IT-002",
     "Fermenter-SPS konnte direkte S7-Verbindung zur Abfüll-SPS herstellen; Segmentierung laut Plan nicht realisiert.",
     "Stacking-Fehler VLAN, ACL fehlte, nicht gegen Referenz-Plan IEC 62443 3-3 geprüft.",
     "closed", "major", "IT/OT Sicherheit", "Werk-01"),
    (13, "WLAN in Produktion unverschlüsselt", "2024-07-08", "SOP-IT-002",
     "SSID „Production_Floor“ ohne WPA2, Klartext-Telemetrie sichtbar.",
     "Rapid-Deploy auf Messegast-Pilot, nie auf Enterprise-WPA3 nachgezogen.",
     "closed", "major", "IT/OT Sicherheit", "Werk-01"),
    (14, "Kein Alarm bei Zugriff außerhalb Arbeitszeit", "2024-08-20", "SOP-IT-002",
     "SCADA-SSH 23:15, SIEM-Regel „nachts OT“ liefert keinen P1-Alarm, nur Statistik-Entry.",
     "Fehlendes Usecase-Playbook, SIEM-Use-Case nicht mit OT-Security-Team abgeglichen.",
     "open", "major", "IT/OT Sicherheit", "Werk-01"),
    (15, "Penetrationstest nicht durchgeführt", "2024-09-01", "SOP-IT-002",
     "Halbjährlicher interner Pentest H1/24 ausgesetzt, Budget-Umverteilung.",
     "Fehlendes Bordmandat, Pentest nicht als Pflicht-Release-Objekt in OT-Plannung hinterlegt.",
     "open", "major", "IT/OT Sicherheit", "Werk-01"),
    (16, "Unbekanntes Gerät im OT-Netz", "2024-10-15", "SOP-IT-002",
     "10.12.47.99 (nicht in Device42) 48h aktiv, Gast-Notebook an Switch SW-ABF-08.",
     "Dienstleister-Bring-Your-Own, kein 802.1X an Access-Port, NAC-Richtlinie nicht scharf genug.",
     "in_review", "major", "IT/OT Sicherheit", "Werk-01"),
    (17, "DNS-Exfiltration möglich", "2024-03-01", "SOP-IT-002",
     "OT→IT DNS-Port 53 voll offen, beliebige Auflösung für IoT-Devices möglich.",
     "Ursprüngliche Notfall-Regel für Patching-Systeme, nie bereinigt.",
     "closed", "major", "IT/OT Sicherheit", "Werk-01"),
    (18, "Switch ohne Authentifizierung", "2024-11-10", "SOP-IT-002",
     "Cisco-Access in Fermentation mit cisco/cisco, SNMP v2c, Telnet-Port 23 an.",
     "Härtungspaket nicht in OT-Master-Image für Cisco 2960 übernommen.",
     "open", "major", "IT/OT Sicherheit", "Werk-01"),
    (19, "VLAN nicht korrekt getrennt", "2024-04-12", "SOP-IT-002",
     "L3-Routing für VLAN 10/20, Fermentation kann direkte SPS-Pings in Abfüll-Subnetz 10.12.30.0/24.",
     "Fehlende „no inter-VLAN“ auf SVI, stattdessen alte Migrationsroute gesetzt.",
     "closed", "major", "IT/OT Sicherheit", "Werk-01"),
    (20, "Remote-Zugriff ohne VPN", "2024-12-01", "SOP-IT-002",
     "Dienstleister baute TeamViewer-Session als Umgehung, Zielsystem SCADA-01.",
     "Fehlende GPO, AppLocker, lokale Admins; Vertrag mit Kunde erlaubt Remote-Tools nicht, nicht überwacht.",
     "in_review", "major", "IT/OT Sicherheit", "Werk-01"),
    (21, "Break-Glass ohne Dokumentation", "2024-06-18", "SOP-IT-003",
     "Aktivierung 15.06. nicht im QMS nachvollziehbar; Erinnerungsmail-Workflow ausstehend.",
     "Fehlendes Tagesabschluss-Ritual, Produktionsleiter dachte, SCADA-Export reicht; Pflichtkurs 2022.",
     "closed", "major", "Notfall/OT", "Werk-01"),
    (22, "Notfall-Token Umschlag beschädigt", "2024-07-25", "SOP-IT-003",
     "Lagerung im Tresor: Umschlag wies Beschleunigungsspuren; Siegel-Integrität fraglich.",
     "Fehlendes wöchentliches Sicht- und Siegel-Log, nur Quartals-Check ursprünglich vorgesehen.",
     "open", "major", "Notfall/OT", "Werk-01"),
    (23, "Break-Glass für nicht-kritischen Fall", "2024-08-05", "SOP-IT-003",
     "Routine-Wartung 08:00 mit Break-Glass startet, trotz verfügbarer Standard-Tickets.",
     "Dringlichkeit falsch eingestuft, Eskalationsspiel während Urlaub nicht kommuniziert.",
     "closed", "major", "Notfall/OT", "Werk-01"),
    (24, "Keine neuen Token nach Break-Glass", "2024-09-12", "SOP-IT-003",
     "Nach 10.09. lagen noch alte Umschlag-IDs, keine Re-Key-Bestellung, Break-Glass-Konto noch aktiv >24h.",
     "Fehlende Orchestrierung, IT-Bestellung an Yubi; Workflow nicht mit ITSM verknüpft.",
     "open", "major", "Notfall/OT", "Werk-01"),
    (25, "Zwei-Umschläge-Prinzip umgangen", "2024-10-20", "SOP-IT-003",
     "Nur PL hat beide Umschläge, QA-Umschlag lag nicht im Soll-Tresor.",
     "Fehlende wöchentliche Inventur der QA-B-Safe, nur jährliches Prüfprotokoll bisher.",
     "closed", "major", "Notfall/OT", "Werk-01"),
    (26, "Tresor-Zugragsprotokoll lückenhaft", "2024-11-18", "SOP-IT-003",
     "3 aufeinanderfolgende Break-Glass-Wochen ohne lückenloses Tresor-Zutrittslog, Kameras 45min off.",
     "Batteriewechsel-Video, Security-Rundgang nicht in OT-Security-Journal hinterlegt; Integration fehlt.",
     "open", "major", "Notfall/OT", "Werk-01"),
    (27, "Notfall-Token abgelaufen, nicht ersetzt", "2024-10-10", "SOP-IT-003",
     "Gültigkeit YubiKey-Serie >36 Monate, laut Richtlinie nicht ausgetauscht, Still-Zustand 15min.",
     "Fehlende Asset-Lifecycle-Koppelung, Token nicht im EAM, nur Excel-Handliste 2021.",
     "closed", "major", "Notfall/OT", "Werk-01"),
    (28, "Schulungsnachweis Break-Glass fehlt", "2024-10-20", "SOP-IT-003",
     "2 Produktions-Shift-Leiter in Liste PL4/5 ohne 2024-Nachweis, Pflichtkurs 2021.",
     "E-Learning-Plattform nicht in HR-Workflow verpflichtet; Excel-Status.",
     "in_review", "major", "Notfall/OT", "Werk-01"),
    (29, "Video-Tresor ausgefallen, Session nicht gestoppt", "2024-10-19", "SOP-IT-003",
     "DVR-Recorder offline, Break-Glass 18:00 durchgeführt, trotzdem 30min längerer OT-Zugang, nicht eskaliert.",
     "Kein harter Stopp, wenn Kamera+Reader nicht synchron, nur Soft-Warn-Flag.",
     "open", "major", "Notfall/OT", "Werk-01"),
    (30, "Umschlag-Nummern nicht fortlaufend geprüft", "2024-10-19", "SOP-IT-003",
     "Fehlende Serien-Nummer #112→#120 Sprung, Möglichkeit Tausch/Diebstahl nicht ausschließbar.",
     "Doppelkauf über zwei Budgetstellen, kein zentraler Siegel-Pool, QA-Kontrolle 6 Mon. verspätet.",
     "open", "major", "Notfall/OT", "Werk-01"),
    (31, "KI-Modell nicht validiert", "2024-08-15", "SOP-IT-004",
     "PM-KI auf SCADA-Export ohne IQ/OQ, nur Data-Science-Notebook, keine SOP-IT-004-Release Matrix.",
     "Ressorcenengpass Q3, Management-Druck auf schnellste ROI-Lösung, QA-Gate umgangen.",
     "open", "critical", "Data Science/OT", "Werk-01"),
    (32, "KI-Empfehlung ohne menschliche Prüfung", "2024-09-05", "SOP-IT-004",
     "Optimierer setzte 25% Rühr-Δ, harte Grenze 10% laut Sollkurve, Override-Taste in HMI inaktiv.",
     "Fehlendes SPS-Clamp, nur Software-Binding; Bug in Human-in-Loop-Flag, Release v0.8.",
     "open", "critical", "Data Science/OT", "Werk-01"),
    (33, "Kein Logging von KI-Aktionen", "2024-07-01", "SOP-IT-004",
     "Model-Serving-API: keine vollständigen requestId→batchId Bindings, nur stdout.",
     "Fehlende MDC-Trace in FastAPI, OT Security Review nicht in CI.",
     "closed", "major", "Data Science/OT", "Werk-01"),
    (34, "KI-Zugriff ohne Freigabe", "2024-10-10", "SOP-IT-004",
     "Data Scientist in IAM-Gruppe KI_AUTOMATE, keine QP-parallel Freigabe im QMS.",
     "Fehlende Trennung Dev/Prod, RBAC-Template 2020 zu breit, HR-Rolle nicht revalidiert.",
     "open", "major", "Data Science/OT", "Werk-01"),
    (35, "KI-Fehlentscheidung mit Produktauswirkung", "2024-11-15", "SOP-IT-004",
     "Rückkopplung pH −0,8, Grenze 0,2, Charge 4711 außerhalb Spezifikation; Freigabestopp, Rückruf-Option.",
     "Fehlendes adversarielles Testing, Regressor nicht kalibriert auf pH-Drift Saison.",
     "open", "critical", "Data Science/OT", "Werk-01"),
    (36, "Kein Human-in-the-Loop bei KI", "2024-12-01", "SOP-IT-004",
     "Automate-Regler ohne Operator-Bestätigung, Betreiber-UI-Flag „immer auto“ fälschlich in Prod.",
     "Merge-Konfigurationsfehler zwischen Staging- und Prod-JSON, QA-Sign-Off fehlend.",
     "open", "critical", "Data Science/OT", "Werk-01"),
    (37, "Regressions-Metrik (MAPE) nach Modell-Update drastisch angestiegen", "2024-10-20", "SOP-IT-004",
     "MLOps-Pipeline: neues scikit-Modell verschlechtert MAPE >18%, trotzdem in Canary nicht gestoppt.",
     "Fehlende harte SLO-Guardrails im Deployment, kein automatischer Rollback, nur E-Mail-Alert an DS.",
     "in_review", "major", "Data Science/OT", "Werk-01"),
    (38, "Training-Daten-Drift nicht überwacht", "2024-10-20", "SOP-IT-004",
     "Fermenter-Druckdaten 2020–2021 als Trainingsquelle, aktuelle Sensor-Drift 12% in Q4 nicht erkannt.",
     "Fehlendes monatliches Drift-Monitoring, nur jährliches manuelles Review, Referenz: SOP-IT-004 §4.2.",
     "open", "major", "Data Science/OT", "Werk-01"),
    (39, "KI-Server Single-Node ohne HA", "2024-10-20", "SOP-IT-004",
     "KISRV01 Ausfall, Predictive-Layer offline, SPS-Rest auf Heuristik, aber QA nicht informiert 40min.",
     "Budget kein Cluster, faktisch DRP nicht getestet; fällt in IT-Risiko, nicht behördenfähig belegt.",
     "closed", "major", "Data Science/OT", "Werk-01"),
    (40, "Erklärbarkeit/SHAP-Export für Audit nicht vorhanden", "2024-10-20", "SOP-IT-004",
     "Behördenanfrage: Begründung pH-Shift; Modell-Black-Box, keine lokalen Shapley-Werte, nur Roh-Log.",
     "Dokupflicht 4.4 nicht in Feature-Map abgebildet, Compliance-Story nur auf Slides, nicht in Git.",
     "in_review", "major", "Data Science/OT", "Werk-01"),
    (41, "Kritischer Patch nicht innerhalb 48h", "2024-09-20", "SOP-IT-005",
     "CVE-2024-1234, CVSS 9,8, SCADA-01, Rollout-Plan nach 96h, SLA-Miss, Risiko-Report an GF.",
     "Fehlendes P1-Wartungsfenster, laufender Batch blockierte Sonntagsslot, Eskalation zu spät.",
     "open", "critical", "IT/OT Patch", "Werk-01"),
    (42, "Patch ohne Test installiert", "2024-06-10", "SOP-IT-005",
     "HMI-Windows-Patch, Bluescreen, Linie 30min, Root-Cause: Test-Bench 2020 nicht in Parity (GPU-Treiber).",
     "Druck durch Audit-Finding, fälschliche Annahme „nur Security Hotfix, kein Reboot-Test nötig“.",
     "closed", "major", "IT/OT Patch", "Werk-01"),
    (43, "Patch während laufender Charge", "2024-07-15", "SOP-IT-005",
     "Fermenter-Patch, Charge 4711 in Phase 2, 2h Still, Temperaturschwankung >0,5K außerhalb SOP-Prod-Note.",
     "Fehlende Rücksprache Batchesystem→OT-Change, nur telefonische Freigabe.",
     "closed", "major", "IT/OT Patch", "Werk-01"),
    (44, "Kein Rollback nach fehlerhaftem Patch", "2024-08-22", "SOP-IT-005",
     "VMware-Snapshot HMI, nicht geprüft, vCenter-Fehler, SPS-Version nicht in Git-Safe.",
     "Backup-Script Windows-HMI, kein vollwertiger Rollback, nur Image monatlich.",
     "open", "major", "IT/OT Patch", "Werk-01"),
    (45, "Vulnerability-Scanner Lizenz abgelaufen", "2024-10-05", "SOP-IT-005",
     "3 Tage kein TACACS/Qualys-Connect, 01.–03.10., keine tagesaktuellen CVE-Sicht, OT-Risiko-Register lückenhaft.",
     "Budgetfreigabe Q2 verzögert, Lizenzteam nicht in Eskalation mit OT-Security, nur IT-NOC-Verteiler.",
     "closed", "major", "IT/OT Patch", "Werk-01"),
]

# CAPA: (num 1-45, title, dev_nr, action_text, owner, due, ext_status) — 035 aus Quelle, +036-045 für 026-030,037-040,045
# Original 1-35 laut sops_data; 36-45 ergänzend.

CAPA_ROWS: list[tuple] = [
    (1, "Automatisiertes Anmeldesystem für Externe", 1,
     "Einführung Jira Service Management, 24h-SLA, Gatekeeper IT-Sec, Reporting an QA wöchentlich.",
     "IT-Leiter", "2024-06-30", "effective"),
    (2, "Initiales Passwort-Reset bei Inbetriebnahme", 2,
     "Maschinen-Checklisten digital, Gate „Standardpasswort geändert, Nachweis Foto+Timestamp“ in MES-Abnahme.",
     "Produktions-Engineering", "2024-08-01", "effective"),
    (3, "2FA für alle externen VPN-Zugänge", 3,
     "FortiGate-Profil, Hardware-Token, Schulung, Policy Enforcement statt reiner Avisierung.",
     "IT-Sicherheit", "2024-12-15", "in_progress"),
    (4, "Zentrale Log-Archivierung mit Alarm", 4,
     "Graylog, 365-Tage, Integritätscheck, Pager an QA bei Puffer<10%.",
     "IT Betrieb", "2024-07-15", "effective"),
    (5, "Regelmäßiges Role-Review (monatlich)", 5,
     "Powershell/AD-Report, Abweichung, automatischer Ticket, QP informiert.",
     "IT+QA", "2024-05-01", "effective"),
    (6, "Zentrale Vertragsdatenbank Dienstleister", 6,
     "Dokumenten-Workflow, Verfallsalarm, CDA, HR-Freigabe, Sanktionstext in Liefervertrag.",
     "QA", "2024-12-31", "open"),
    (7, "Zeitliche Sperre externe OT-Zugriffe", 7,
     "Firewall-Policy, Zeitfenster, QA-Ausnahme, SIEM-Alert.",
     "IT Netzwerk", "2024-11-30", "in_progress"),
    (8, "Zertifikatsbasierte Service-Accounts", 8,
     "Migrationsplan Chromatograph, PKI, Rotation, Sperre Passwort-Login.",
     "IT OT", "2024-04-30", "effective"),
    (9, "SCADA-Logging Read-only", 9,
     "WinCC-Parametrierung, Historian-Tag, QA-Abnahme, Testplan.",
     "IT+Produktion", "2024-12-15", "in_progress"),
    (10, "Vier-Augen-Workflow Admin-Zugriff", 10,
     "ServiceNow, duale Genehmiger IT+QP, 4-Augen-Policy technisch, Audit Trail.",
     "QA+IT", "2024-03-01", "effective"),
    (11, "Firewall-Regel-Review", 11,
     "Voll Review, Least-Privilege, Doku, Re-Test Pentest, SIEM-Use-Case-Update.",
     "IT-Sicherheit", "2024-06-15", "effective"),
    (12, "Segmentierung nach IEC 62443", 12,
     "Neuplan, VLAN, ACL, OT-Test, Freigabe QA, Change-Package.",
     "IT OT", "2024-07-31", "effective"),
    (13, "WPA3 für Produktions-WLAN", 13,
     "RADIUS, 802.1X, WPA3-Enterprise, Gerätezertifikat, alte SSID deaktivieren.",
     "IT", "2024-08-15", "effective"),
    (14, "SIEM-Regeln Arbeitszeit", 14,
     "Korreliere OT-Session+HR-Schicht+Kalender, Alarm P2 inkl. Telefon-Bridge.",
     "IT-SOC", "2024-10-31", "open"),
    (15, "Pentest extern (SEC Consult)", 15,
     "SOW, Scope, Bericht, CAPA-Kaskade, Frist Q1-25.",
     "IT-Leiter", "2025-03-31", "open"),
    (16, "Inventar OT-Assets Device42", 16,
     "NAC-Quelle, wöchentl. Diff, unbekannte IP sofort in CAPA, OT-Security-Review.",
     "IT OT", "2024-12-15", "in_progress"),
    (17, "DNS-Filterung", 17,
     "Nur whitelisted Forwarder, DNS-Proxy, Logging, SIEM, OT-Sanity.",
     "IT", "2024-04-15", "effective"),
    (18, "Switch-Hardening", 18,
     "AAA, SNMPv3, Passwort, Telemetrie, OT-Master, Rollout.",
     "IT OT", "2024-12-31", "open"),
    (19, "VLAN-Routing-Review", 19,
     "SVI abschalten, nur L3-OT-DC, Doku, Penetration retest, QA-Freigabe.",
     "IT", "2024-05-15", "effective"),
    (20, "Verbot unautorisierte Remote-Tools", 20,
     "AppLocker, LAPS, Dienstleister-Policy, rechtliche AGB.",
     "IT", "2025-01-31", "in_progress"),
    (21, "Autom. Ticket Break-Glass", 21,
     "ITSM-Regel, QMS-Bridge, 24h-Follow-up, Eskalation GF, KPI.",
     "IT", "2024-07-31", "effective"),
    (22, "Physische Sicherheit Umschläge", 22,
     "Wöchentliche Sicht, Siegel, Serien, Safe dual-control, Foto, Audit.",
     "QA", "2024-08-31", "open"),
    (23, "Definition kritischer Break-Glass-Fall", 23,
     "SOP-IT-003, Beispiele, Schulung, Szenario-Test.",
     "QA", "2024-09-15", "effective"),
    (24, "Autom. Token-Bestellung", 24,
     "Yubi, Bestellkette ITSM, 48h, QA-Sign, Archiv, Rollback-Plan.",
     "IT", "2024-10-31", "open"),
    (25, "Trennung Umschläge (QA-Safe)", 25,
     "Ablage QA-Safe, Dual Key, wöchentl. Kollaborationslog, Foto, Revision.",
     "QA", "2024-11-15", "implemented"),
    (26, "KI-Validierungspflicht (SOP-Ref.)", 31,
     "IQ/OQ, Worst-Case, Behörden-Dossier, Sperre Prod bis Freigabe.",
     "QA", "2024-10-31", "in_progress"),
    (27, "Harte Grenzen in SPS", 32,
     "Clamp, Safety-Check, FMEA, Retest, Human-Override, Retrofit.",
     "Data Science+IT", "2024-10-15", "implemented"),
    (28, "API-Logging vollumfänglich", 33,
     "OTEL, MDC, Immutable Store, 7+ Jahre GMP, QA-Test.",
     "IT", "2024-08-15", "effective"),
    (29, "IAM KI_Rollen trennen", 34,
     "KI_READ/RECOMMEND/AUTOMATE, Freigabepath QP, PAM, JEA.",
     "IT+QA", "2024-12-15", "in_progress"),
    (30, "Adversarielle KI-Tests/Neu-Validierung", 35,
     "Puffer pH, Monte-Carlo, Rückruf-Play, Behörde-Template.",
     "Data Science", "2025-01-31", "open"),
    (31, "Human-in-the-Loop Zwang", 36,
     "UI+SPS, doppelter Ack, SOP, Schulung, Audit.",
     "QA", "2025-02-28", "open"),
    (32, "Wartungsfenster P1-Patch", 41,
     "Sonntag 02–06, P1, Eskalation Batches, GF-Memo.",
     "Produktion+IT", "2024-10-31", "open"),
    (33, "Testumgebung in Parity", 42,
     "Klon HMI+SCADA+SPS, tägliches Sync, Patch-Dry-Run, QA-Abnahme.",
     "IT", "2024-07-31", "effective"),
    (34, "Patch-Workflow Batcheschutz", 43,
     "QMS, keine OT-Change ohne Batchboard-Freigabe, Eskalation.",
     "QA", "2024-08-31", "effective"),
    (35, "Backup+Restore-Test vPatch", 44,
     "Snapshot+File+SPS-Export, monatl. Wiederanlauf, KPI, Audit.",
     "IT", "2025-01-31", "in_progress"),
    (36, "Tresor-Video-Resilienz + harter Stopp", 26,
     "DVR+Reader Sync, SOP, Alarm Stopp, QA Monatsreview, 24/7-Bridge.",
     "IT-Sicherheit+QA", "2025-02-15", "open"),
    (37, "Token-Lifecycle in EAM", 27,
     "Yubi-Serien, HR-Pflicht, 24-Monat-Roll, Ticket-Autobestell, QA.",
     "IT+HR", "2024-12-20", "effective"),
    (38, "E-Learning Pflichtkurs", 28,
     "LMS, HR-Block, Nachweis, Szenario, Audit Trail.",
     "HR+QA", "2024-11-15", "in_progress"),
    (39, "KI-Server HA + DRP-Test", 39,
     "K8s+LB, 15min RTO, quartalsweise Übung, behördenfähige Doku.",
     "IT+OT", "2025-01-20", "open"),
    (40, "MLOps Drift/SHAP-Export", 37,
     "Evidently, Auto-Rollback, SLO, Behördenpaket, QA-Freigabe-Job.",
     "Data Science+QA", "2025-02-01", "in_progress"),
    (41, "Lizenz/Scanner Eskalation OT", 45,
     "Auto-Renew, Budget, OT-Sec-Pager, Daily Health-Check, Compliance.",
     "IT+Finance", "2024-10-15", "effective"),
    (42, "Erklärbarkeits-Register KI (SHAP+Git)", 40,
     "DVC, SHAP, Release-Tags, Audit-View, SOP-IT-004-Annex, Unterzeichner QP.",
     "Data Science+QA", "2025-02-20", "open"),
    (43, "DVR/Tresor Integration SIEM", 29,
     "Kamera+Reader+Break-Glass Korrelation, P1 bei Out-of-Sync, Playbook, QA-Alarm.",
     "IT-SOC+QA", "2024-12-10", "open"),
    (44, "Umschlagserien-Pool zentral (QA+PL)", 30,
     "Einlieferung, lückenlose Kette, wöchentl. Sicht, Inventur+Forensik, SAP MM.",
     "QA", "2024-12-05", "in_progress"),
    (45, "Drift-Monitor Pipeline", 38,
     "Feldmonitoring monatlich, Stopp Canary, SOP, QA-Freigabe, Trainings-Refresh.",
     "Data Science+QA", "2025-01-10", "open"),
]

# Audits: (n, name, adate, finding, capa_num, sev, accept)
AUDIT_ROWS: list[tuple] = [
    (1, "EMA Inspektion", "2024-03-15", "Externe Zugänge: kein 24h-Vorlaufnachweis, Ticket fehlt, Referenz SOP-IT-001/4.2.",
     1, "major", "accepted"),
    (2, "Internes Audit Q2", "2024-04-20", "Standardkonto Abfüllung admin/admin, Referenz SOP-IT-001/4.3.",
     2, "major", "accepted"),
    (3, "FDA Inspektion", "2024-06-10", "Remote-OT ohne 2FA, Dienstleister, CAPA-003 offen, Referenz 4.2/4.1.",
     3, "critical", "open"),
    (4, "Internes Audit Q3", "2024-07-15", "3-Tage-Loglücke OT, Graylog, Referenz 4.4, Charge-Nachsicht.",
     4, "major", "accepted"),
    (5, "Kundenaudit Großhändler", "2024-05-05", "Operator-Admin, Rollen, Referenz 4.1, IAM, CAPA-005.",
     5, "minor", "accepted"),
    (6, "Regierungspräsidium", "2024-09-20", "NetzTech ohne CDA, 4.2, Vertrags-Workflow.",
     6, "major", "open"),
    (7, "Internes Audit Q4", "2024-10-01", "Open SSH IT→OT zu breit, 4.1, SOP-IT-002.",
     11, "major", "accepted"),
    (8, "EMA Inspektion", "2024-11-05", "Keine harte Trennung Fermenter/Abfüllung, IEC 62443, CAPA-012.",
     12, "critical", "accepted"),
    (9, "FDA Inspektion", "2024-12-01", "WPA unverschlüsselt, 4.2, CAPA-013.",
     13, "major", "accepted"),
    (10, "Internes Audit Q1-25", "2025-01-10", "Nacht-OT, SIEM, CAPA-014, Referenz 4.3.",
     14, "minor", "open"),
    (11, "Zert. ISO-27001", "2024-08-20", "Pentest fällig, 4.3, CAPA-015.",
     15, "major", "open"),
    (12, "Internes Q2-24", "2024-06-15", "10.12.47.99 unbekannt, 4.3, CAPA-016.",
     16, "major", "in_progress"),
    (13, "EMA", "2024-09-25", "Break-Glass nicht dokumentiert, 3.3, CAPA-021.",
     21, "major", "accepted"),
    (14, "FDA", "2024-10-30", "Beschädigter Umschlag, 3.1, CAPA-022.",
     22, "minor", "open"),
    (15, "Internes Q3-24", "2024-11-20", "KI-Validierungsdossier fehlt, SOP-IT-004, CAPA-026.",
     26, "critical", "open"),
    (16, "Behörde (Bundesland)", "2024-12-10", "KI pH, Charge, CAPA-030, EU-GMP, Behörde.",
     30, "critical", "open"),
    (17, "Kundenaudit", "2025-01-05", "HITL fehlt, CAPA-031, 4.3, FDA-Erwartung.",
     31, "major", "open"),
    (18, "Internes Q4-24", "2024-12-15", "CVE, 48h, CAPA-032, SOP-IT-005.",
     32, "major", "open"),
    (19, "EMA 2025", "2025-01-20", "Patch, Charge, CAPA-034, 3.3, QA-Nachsicht.",
     34, "major", "accepted"),
    (20, "FDA 2025", "2025-02-01", "Kein Rollback, CAPA-035, 3.2, Backup, QA-Plan.",
     35, "major", "in_progress"),
]

# Decisions: n, Titel, Datum, audit_n (1–20), (ref_dev_num, ref_capa_num), Entscheidung, Risiko, Begründung, primäre SOP-Nummer
DECISION_ROWS: list[tuple] = [
    (1, "Stilllegung Abfüllmaschine (ABF-01)", "2024-07-21", 2, (2, 2),
     "Abfülllinie 48h still, Standardpasswörter zurückgesetzt, Schulung, Re-IB nach QA, CAPA-IT-002.",
     "hoch", "Standard-Default zulasten SOP-IT-001/4.3, potenzielles GMP- und Produkterechtsrisiko.", "SOP-IT-001"),
    (2, "Sperre Dienstleister (NetTech GmbH)", "2024-08-12", 3, (3, 3),
     "Remote-OT blockiert, bis 2FA und Forti-Profil vollständig mit CAPA-IT-003 belegt sind; Re-Entry-Checklist.",
     "mittel", "Wiederholter 2FA-Verstoß, regulatorische Sicht auf Remote-Zugriff SOP-IT-001/4.2.", "SOP-IT-001"),
    (3, "Charge #4682 Freigabe mit Stabilitätsauflage", "2024-06-14", 4, (4, 4),
     "Freigabe 6 Mon. Stabilität, erweiterte Rückverfolgung, CAPA-IT-004 schließt Log-Archiv bis Q4.",
     "mittel", "Produkt nicht betroffen, aber 4.4-Loglücke – dokumentarisch nachvollziehbar aufgeladen.", "SOP-IT-001"),
    (4, "Rückruf Charge #4711 (Hyluron)", "2024-11-16", 16, (35, 30),
     "Vollständiger Markt-Rückruf, Quarantäne, Behörden-Template, SOP-IT-004, CAPA-IT-030.",
     "kritisch", "pH-Soll verletzt, Patientensicherheit, EU GMP, FDA-Erwartung, CAPA-IT-030, DEV-IT-035.", "SOP-IT-004"),
    (5, "Deaktivierung KI-Automate standortweit", "2024-11-16", 16, (35, 30),
     "Bis abgeschlossene Re-Validierung und SPS-Clamp, Betrieb nur Heuristik/Manual, CAPA-IT-030/031.",
     "kritisch", "Wiederholhäufige KI-Grenzverletzung, pH, Charge, CAPA-IT-030, 031, 4711.", "SOP-IT-004"),
    (6, "Externe Firewall-Revision beauftragen", "2024-06-16", 7, (11, 11),
     "Auftragsvergabe, Scope OT/IT, 6 Wochen, Least-Privilege, Abnahme QA+CAPA-IT-011.",
     "mittel", "Interne OT-Cap, SSH-Befund AUD-IT-007, 4.1, CAPA-IT-011, SOP-IT-002.", "SOP-IT-002"),
    (7, "Budget 50.000€ SIEM-Upgrade (Splunk)", "2024-10-15", 10, (14, 14),
     "CFO/OT frei, SOC-Regeln, Night-OT-Alarm, CAPA-IT-014, 4.3, AUD-IT-010-Befund.",
     "mittel", "Fehlende 20:00-Alarmierung, 4.3, SIEM, FDA-Audit, CAPA-IT-014, DEV-IT-014.", "SOP-IT-002"),
    (8, "Pentest extern SEC Consult (30k) Q1/25", "2024-08-25", 11, (15, 15),
     "SOW, OT-Scope, BERICHT, CAPA-Triage, 4.3, 27001, ISO, CAPA-IT-015, 15, AUD-IT-011.",
     "mittel", "Interner Pentest-Backlog, FDA/27001, CAPA-IT-015, 15, Halbjahres, DEV-IT-015.", "SOP-IT-002"),
    (9, "Beschleunigter WPA3/802.1X–Rollout WLAN-OT", "2024-12-01", 9, (13, 13),
     "Fertigstellung Enterprise-WLAN inkl. 802.1X und WPA3 spätestens 31.12.2024, CAPA-IT-013 und technische Abnahme durch Networking, Nachweis in FDA-Antwortdossier (AUD-IT-009, SOP-IT-002/4.2, DEV-IT-013).",
     "mittel", "Befund unverschlüsselter Produktions-SSID, direkter Bezug zu SOP-IT-002, CAPA-IT-013, FDA-Erwartung 21 CFR 11-nahe Sicherheitskontrolle Netzwerks.", "SOP-IT-002"),
    (10, "Umschlag- und Token-Programm (Tresor, Break-Glass)", "2024-09-20", 14, (22, 22),
     "Neuversiegelte Umschäge mit lückenloser Seriennr., wöchentliche Sichtkontrolle, zweiter Safe bei QA, Eskalation bei Bruch, CAPA-IT-022 (SOP-IT-003/3.1, DEV-IT-022, AUD-IT-014).",
     "niedrig", "Integrität der physischen Krypto-Träger, Missbrauchs- und Beweiskette für Behörde und TÜV, direkter Bezug SOP-IT-003, CAPA-IT-022, DEV-IT-022.", "SOP-IT-003"),
    (11, "KI-Validierungs-Stop: keine weitere Freigabe ohne OQ-Report", "2024-10-31", 15, (31, 26),
     "Bis 31.03.2025 Re-Validierung laufender Modelle, Sperrung neuer Produktiv-Freigaben, CAPA-IT-026 und QA-Programmplan, Audit AUD-IT-015 (SOP-IT-004, DEV-IT-031, CAPA-IT-026, FDA-Befund).",
     "kritisch", "Fehlende IQ/OQ/DQ-Kette für PM-KI, EMA- und FDA-Referenz, regulatorischer Druck, direkter Bezug SOP-IT-004 §4.2 und SOP-IT-001/OT-Zugriff auf KI-Schnittstellen.", "SOP-IT-004"),
    (12, "Fester wöchentlicher P1-Patch-Slot (So. 02:00–06:00)", "2024-10-15", 18, (41, 32),
     "Dauerhafter Kalenderplatz, Eskalation bei CVE >9,0 und Überschreiten der 48h-Frist an GF, Bindeglied CAPA-IT-032, AUD-IT-018, DEV-IT-041, SOP-IT-005/3.1.",
     "mittel", "Hochkritische CVE, SLA-Patch, Produktion und IT einvernehmlich, direkter Bezug SOP-IT-005 und Patch-Risikomatrix.", "SOP-IT-005"),
    (13, "80.000 € Testumgebung in Produktions-Parity", "2024-07-31", 19, (42, 33),
     "Invest in identische HMI+SCADA+SPS-Parity, täglicher Synchron, Dry-Run vor jedem P1, CAPA-IT-033, Befund Patch ohne Test (DEV-IT-042, AUD-IT-019, SOP-IT-005/3.2, Charge #4711).",
     "mittel", "Bluescreen-Beinahe-Produktionsstopp, direkter Bezug SOP-IT-005 Testpflicht, CAPA-IT-033, 3.2, FDA-Erwartung an reproduzierbare Prüfung.", "SOP-IT-005"),
    (14, "Dienstleister-AGB, CDA, Vertragsstrafen-Update (5.000 €/Verstoß)", "2024-09-30", 6, (6, 6),
     "Juristisches Muster, HR-Einkauf-Workflow, Sperre bei Nichtunterzeichnung, GMP- und OT-Klausel, Verweis SOP-IT-001/4.2, CAPA-IT-006, Befund AUD-IT-006, DEV-IT-006, RP-Vorgaben.",
     "niedrig", "Rechtliches Restrisiko ohne CDA, regulatorisch nachvollziehbar, direkter Bezug SOP-IT-001 und Lieferkette OT.", "SOP-IT-001"),
    (15, "25.000 € DRP: Backup, Restore, monatlicher Prüf-VPatch", "2025-01-15", 20, (44, 35),
     "Budget für Snapshot-Automatisierung+Storage, monatlicher SPS/HMI-Restore, KPI im QMS, Verknüpfung CAPA-IT-035, Befund FDA AUD-IT-020, kein funktionierender Rollback, DEV-IT-044, SOP-IT-005/3.2.",
     "mittel", "Fehlende Rückfallebene, Patch-Risiko in OT, GMP-Traceability, direkter Bezug SOP-IT-005, CAPA-IT-035, 3.2, FDA-Patch-Expectation-Letter-Referenzframework.", "SOP-IT-005"),
]
